config/routes.rb
Dallashappyhour::Application.routes.draw do
  
  resources :happies
  root 'happies#index'

end

app/models/happy.rb
class Happy < ActiveRecord::Base
	self.per_page = 20

	searchable do
		text :name, :day, :deal, :boost => 10

		string :day_str do
  			day
		end

	end

	


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/happies_controller.rb
class HappiesController < ApplicationController
  before_action :set_happy, only: [:show, :edit, :update, :destroy]

  # GET /happies
  def index
    @search = Happy.search do
      fulltext params[:search]
      facet(:day_str)
      paginate :page => 1, :per_page => 550
    end
    @happies = Happy.where(id: @search.results.map(&:id)).page(params[:page])
  end

  # GET /happies/1
  def show
  end

  # GET /happies/new
  def new
    @happy = Happy.new
  end

  # GET /happies/1/edit
  def edit
  end

  # POST /happies
  def create
    @happy = Happy.new(happy_params)

    if @happy.save
      redirect_to @happy, notice: 'Happy was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /happies/1
  def update
    if @happy.update(happy_params)
      redirect_to @happy, notice: 'Happy was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /happies/1
  def destroy
    @happy.destroy
    redirect_to happies_url, notice: 'Happy was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_happy
      @happy = Happy.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def happy_params
      params.require(:happy).permit(:name, :day, :phonenumber, :deal, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/happies_helper.rb
module HappiesHelper
end

app/views/happies/_form.html.erb
<%= bootstrap_form_for(@happy) do |f| %>
  <% if @happy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@happy.errors.count, "error") %> prohibited this happy from being saved:</h2>

      <ul>
      <% @happy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    
    <%= f.text_field :name, value: "Bar or Restaurant Name" %>

    <%= f.form_group :day, :class => "radio-inline", label: { text: "Day"} do %>
        <%= f.radio_button :day, "Monday", label: "Monday", checked: true %>
        <%= f.radio_button :day, "Tuesday", label: "Tuesday" %>
        <%= f.radio_button :day, "Wednesday", label: "Wednesday" %>
        <%= f.radio_button :day, "Thursday", label: "Thursday" %>
        <%= f.radio_button :day, "Friday", label: "Friday" %>
        <%= f.radio_button :day, "Saturday", label: "Saturday" %>
        <%= f.radio_button :day, "Sunday", label: "Sunday" %>
    <% end %>

    <%= f.text_field :phonenumber, value: "Ex: 2142225555, No () or - or spaces" %>

    <%= f.text_field :deal, value: "Happy Hour", label: "Happy Hour/Brunch Special" %>

    
    <%= f.form_group :location, :class => "radio-inline", label: { text: "Location"} do %>
      <%= f.radio_button :location, "Knox/Henderson", label: "Knox/Henderson", checked: true %>
        <%= f.radio_button :location, "Greenville", label: "Greenville" %>
        <%= f.radio_button :location, "Deep Ellum", label: "Deep Ellum" %>
        <%= f.radio_button :location, "Uptown", label: "Uptown" %>
        <%= f.radio_button :location, "Downtown", label: "Downtown" %>
        <%= f.radio_button :location, "Bishop Arts", label: "Bishop Arts" %>
        <%= f.radio_button :location, "Trinity Groves", label: "Trinity Groves" %>
        <%= f.radio_button :location, "Addison", label: "Addison" %>
        <%= f.radio_button :location, "SMU", label: "SMU" %>
    <% end %>





  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/happies/edit.html.erb
<h1>Editing happy</h1>

<%= render 'form' %>

<%= link_to 'Show', @happy %> |
<%= link_to 'Back', happies_path %>

app/views/happies/index.html.erb
<div class = "row">
  <div class = "col-md-12 col-xs-12">
    <center><img style = "width: 50%;" src="/assets/dh.png"></center>
  </br>
    <%= form_tag happies_path, :method => :get do %>
    
  
      <%= text_field_tag :search, params[:search],
       :placeholder => 'Search by Day, Bar, or Brunch!', :class => 'form-control', 
       :style => 'width: 70%; margin-left: 6em;' %>
      <%= submit_tag "Search", :name => nil,
       :class => 'btn btn-success btn-sm', 
       :style => 'margin-top: -2.75em; margin-right: 8.7em; float:right; width: 10%; height: 2.75em;'%>
  <% end %>
  <%#= link_to("Cant find your bar?", new_happy_path) %>
  <center><%= will_paginate @posts, :style => 'margin-top: -0.2em;' %></center>
  <center><%= link_to("Reset", root_path, :style => 'margin-top: -1em;') %></center>

    <div class = "table-responsive">
    
    <table class = "table table-striped">
      <thead>
        <tr>
          <th>Bar Name</th>
          <th>Day</th>
          <th>Location</th>
          <th>Deals</th>
          <th>Phone Number</th>
        </tr> 
      </thead>
      <tbody>
    
    <% @happies.order("day").each do |happy| %>
          <tr>
            <td><%= happy.name %></td>
            <td><%= happy.day %></td>
            <td><%= happy.location %></td>
            <td><%= happy.deal %></td>
            <td><%= happy.phonenumber %></td>
          </tr>
      <% end %>
    </tbody>
  </table>

  <center><%= will_paginate @posts %></center>
  <center><%= link_to("Reset", root_path) %></center>
 
</br>
</br>
  <center><small>Flip Studios</small></center>
  

  </div>
  </div>
</div>





<!--<h1>Listing happies</h1>

    <%# @happies.each do |happy| %>
      <tr>
        <td><%#= link_to 'Show', happy %></td>
        <td><%#= link_to 'Edit', edit_happy_path(happy) %></td>
        <td><%#= link_to 'Destroy', happy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
 

<%#= link_to 'New Happy', new_happy_path %>-->

app/views/happies/new.html.erb
<div class = "row">
  <div class = "col-md-12 col-xs-12">
<h1>New happy</h1>

<%= render 'form' %>
</br>
<%= link_to 'Back', happies_path %>

	</div>
</div>

app/views/happies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_happy_path(@happy) %> |
<%= link_to 'Back', happies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dallashappyhour</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <!-- Start of Woopra Code -->
<script>
(function(){
    var t,i,e,n=window,o=document,a=arguments,s="script",r=["config","track","identify","visit","push","call","trackForm","trackClick"],c=function(){var t,i=this;for(i._e=[],t=0;r.length>t;t++)(function(t){i[t]=function(){return i._e.push([t].concat(Array.prototype.slice.call(arguments,0))),i}})(r[t])};for(n._w=n._w||{},t=0;a.length>t;t++)n._w[a[t]]=n[a[t]]=n[a[t]]||new c;i=o.createElement(s),i.async=1,i.src="//static.woopra.com/js/w.js",e=o.getElementsByTagName(s)[0],e.parentNode.insertBefore(i,e)
})("woopra");

woopra.config({
    domain: 'www.dallashappies.com'
});
woopra.track();
</script>
<!-- End of Woopra Code -->

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-54071313-1', 'auto');
  ga('send', 'pageview');

</script>

</head>
</br>
<body>

<div class = "container">
<%= yield %>
</div>
</body>
</html>